export const GAME = {
  BASE_SPEED: 200,
  MAX_SPEED: 500,
  BOOST_MULTIPLIER: 1.5,
  MAX_ALTITUDE: 2000,
  INITIAL_ALTITUDE: 100,
  STAR_COLLECT_RADIUS: 15,
  PROJECTILE_SPEED: 200,
  PROJECTILE_LIFETIME: 3,
} as const;

export const COLORS = {
  SKY_BLUE: '#87CEEB',
  TURTLE_GREEN: '#2ECC71',
  BOOST_ORANGE: '#FF6B35',
  STAR_GOLD: '#FFD700',
  HUD_CYAN: '#7FDBFF',
  PANEL_DARK: '#1A1A2E',
  WATER: '#1E90FF',
  SAND: '#F4D03F',
  GRASS: '#27AE60',
  MOUNTAIN: '#8B4513',
  SNOW: '#FFFFFF',
} as const;

export const TERRAIN = {
  CHUNK_SIZE: 64,
  SCALE: 0.02,
  HEIGHT_SCALE: 300,
  ACTIVE_RANGE: 1,
} as const;

export const CAMERA = {
  FOLLOW_DISTANCE: 20,
  FOLLOW_HEIGHT: 8,
  LERP_SPEED: 3,
  BANK_FACTOR: 0.3,
} as const;
