#!/usr/bin/env bash
# App Store preflight for Turtle Flight.
#
#   scripts/preflight.sh            # static checks + Release build + tests (needs Xcode)
#   scripts/preflight.sh --no-build # static checks only (what CI runs on Linux-free steps)
#
# Exits non-zero on the first failed check. Run it before Product → Archive.
set -euo pipefail
cd "$(dirname "$0")/.."

fail() { echo "❌ $*" >&2; exit 1; }
ok()   { echo "✅ $*"; }

# ---- 1. Info.plist essentials ------------------------------------------------
PLIST=TurtleFlight/Info.plist
for key in CFBundleShortVersionString CFBundleVersion NSMotionUsageDescription \
           NSPhotoLibraryAddUsageDescription ITSAppUsesNonExemptEncryption \
           UILaunchScreen UIRequiredDeviceCapabilities CFBundleLocalizations; do
  grep -q "<key>$key</key>" "$PLIST" || fail "Info.plist missing $key"
done
ok "Info.plist has version, usage descriptions, launch screen, capabilities"

# ---- 2. Privacy manifest -----------------------------------------------------
MANIFEST=TurtleFlight/PrivacyInfo.xcprivacy
grep -q "NSPrivacyAccessedAPICategoryUserDefaults" "$MANIFEST" || fail "PrivacyInfo missing UserDefaults reason"
grep -q "<key>NSPrivacyTracking</key>" "$MANIFEST" || fail "PrivacyInfo missing NSPrivacyTracking"
ok "PrivacyInfo.xcprivacy present with required-reason entries"

# ---- 3. Localizations: every declared locale has both .strings files --------
LOCALES=$(python3 - <<'PY'
import re
s=open('TurtleFlight/Info.plist').read()
block=re.search(r'<key>CFBundleLocalizations</key>\s*<array>(.*?)</array>', s, re.S).group(1)
print(' '.join(re.findall(r'<string>([^<]+)</string>', block)))
PY
)
for loc in $LOCALES; do
  [ -f "TurtleFlight/Resources/$loc.lproj/Localizable.strings" ] || fail "missing $loc Localizable.strings"
  [ -f "TurtleFlight/Resources/$loc.lproj/InfoPlist.strings" ]   || fail "missing $loc InfoPlist.strings"
done
python3 - <<'PY'
import re,sys
locs=re.findall(r'<string>([^<]+)</string>', re.search(r'<key>CFBundleLocalizations</key>\s*<array>(.*?)</array>', open('TurtleFlight/Info.plist').read(), re.S).group(1))
def keys(loc,name):
    return set(re.findall(r'^"([^"]+)"\s*=', open(f'TurtleFlight/Resources/{loc}.lproj/{name}').read(), re.M))
en=keys('en','Localizable.strings'); eni=keys('en','InfoPlist.strings')
for loc in locs:
    if keys(loc,'Localizable.strings')!=en: sys.exit(f"Localizable.strings key mismatch: {loc}")
    if keys(loc,'InfoPlist.strings')!=eni: sys.exit(f"InfoPlist.strings key mismatch: {loc}")
print(f"   {len(locs)} locales, {len(en)} Localizable keys, {len(eni)} InfoPlist keys")
PY
ok "Localization files at parity for: $LOCALES"

# ---- 4. App icon: 1024 marketing slot, no alpha ------------------------------
ICON_DIR=TurtleFlight/Assets.xcassets/AppIcon.appiconset
grep -q '"1024x1024"' "$ICON_DIR/Contents.json" || fail "AppIcon missing 1024x1024 marketing slot"
ok "AppIcon set has the 1024×1024 marketing icon"

# ---- 5. project.yml: entitlements + no committed xcodeproj --------------------
grep -q "com.apple.developer.game-center" project.yml || fail "project.yml missing Game Center entitlement"
grep -q "ubiquity-kvstore-identifier" project.yml || fail "project.yml missing iCloud KVS entitlement"
if git ls-files --error-unmatch TurtleFlight.xcodeproj >/dev/null 2>&1; then
  fail "TurtleFlight.xcodeproj is committed — it must be generated by xcodegen"
fi
ok "project.yml entitlements present; xcodeproj not committed"

# ---- 6. Privacy policy + submission doc exist --------------------------------
[ -f PRIVACY.md ] || fail "PRIVACY.md missing"
[ -f docs/APP_STORE_SUBMISSION.md ] || fail "docs/APP_STORE_SUBMISSION.md missing"
ok "PRIVACY.md and submission checklist present"

if [ "${1:-}" = "--no-build" ]; then
  echo "Static preflight passed (build skipped)."
  exit 0
fi

# ---- 7. Release build + tests (macOS with Xcode) ------------------------------
command -v xcodegen >/dev/null || fail "xcodegen not installed (brew install xcodegen)"
xcodegen generate
DEVICE=$(xcrun simctl list devices available | grep -E "iPhone [0-9]+" | tail -1 | sed -E 's/^ *([^(]+) \(.*/\1/' | xargs)
[ -n "$DEVICE" ] || fail "no iPhone simulator available"
echo "Using simulator: $DEVICE"
xcodebuild build -project TurtleFlight.xcodeproj -scheme TurtleFlight \
  -destination "platform=iOS Simulator,name=$DEVICE" -configuration Release \
  CODE_SIGNING_ALLOWED=NO -quiet
ok "Release build succeeded"
xcodebuild test -project TurtleFlight.xcodeproj -scheme TurtleFlight \
  -destination "platform=iOS Simulator,name=$DEVICE" -quiet
ok "All tests passed"
echo "Preflight passed. Next: Xcode → Product → Archive (see docs/APP_STORE_SUBMISSION.md)."
